const express = require('express')
const { getRewards, getRewardById, createReward, updateReward, contributeToReward, getRewardProgress, redeemReward, approveReward, rejectReward, archiveReward, cancelReward, requestContributionRefund, approveContributionRefund, rejectContributionRefund, getRefundRequests} = require('../controllers/rewardController')
const auth = require('../middleware/auth')
const roleCheck = require('../middleware/roleCheck')
const validate = require('../middleware/validate')
const validateQuery =require('../middleware/validateQuery')
const {createRewardSchema, updateRewardSchema, approveRewardSchema, contributeSchema, getRewardQuerySchema} = require('../validators/rewardSchemas')

const router = express.Router()
router.get('/', auth, validateQuery(getRewardQuerySchema), getRewards)
router.post('/', auth,validate(createRewardSchema), createReward)
router.get('/refund-requests', auth, roleCheck('parent'), getRefundRequests)
router.get('/:id', auth, getRewardById)
router.patch('/:id', auth, roleCheck('parent'), validate(updateRewardSchema), updateReward)
router.patch('/:id/approve', auth, roleCheck('parent'), validate(approveRewardSchema), approveReward)
router.patch('/:id/reject', auth, roleCheck('parent'), rejectReward)
router.patch('/:id/cancel', auth, roleCheck('parent'), cancelReward)
router.patch('/:id/archive', auth, roleCheck('parent'), archiveReward)
router.post('/:id/contribute', auth, roleCheck('child'), validate(contributeSchema), contributeToReward)
router.get('/:id/progress', auth, getRewardProgress)
router.post('/:id/redeem', auth, roleCheck('parent'), redeemReward)
router.patch('/:id/request-refund', auth, roleCheck('child'), requestContributionRefund)
router.patch('/:id/approve-refund/:childId', auth, roleCheck('parent'), approveContributionRefund)
router.patch('/:id/reject-refund/:childId', auth, roleCheck('parent'), rejectContributionRefund)

module.exports = router