const express = require('express')
const { getRewards, getRewardById, createReward, updateReward, contributeToReward, getRewardProgress, redeemReward, approveReward, rejectReward, setRewardFunded, archiveReward, cancelReward, refundAllContributions, requestContributionRefund, approveContributionRefund, rejectContributionRefund, cancelContributionRefund, getRefundRequests} = require('../controllers/rewardController')
const { getNotes: getRewardNotes, addNote: addRewardNote } = require('../controllers/rewardNoteController')
const auth = require('../middleware/auth')
const roleCheck = require('../middleware/roleCheck')
const validate = require('../middleware/validate')
const validateQuery =require('../middleware/validateQuery')
const {createRewardSchema, updateRewardSchema, approveRewardSchema, contributeSchema, getRewardQuerySchema} = require('../validators/rewardSchemas')
const { createRewardNoteSchema } = require('../validators/rewardNoteSchemas')

const router = express.Router()
router.get('/', auth, validateQuery(getRewardQuerySchema), getRewards)
router.post('/', auth,validate(createRewardSchema), createReward)
router.get('/refund-requests', auth, roleCheck('parent'), getRefundRequests)
router.get('/:id', auth, getRewardById)
router.patch('/:id', auth, roleCheck('parent'), validate(updateRewardSchema), updateReward)
router.patch('/:id/approve', auth, roleCheck('parent'), validate(approveRewardSchema), approveReward)
router.patch('/:id/reject', auth, roleCheck('parent'), rejectReward)
router.patch('/:id/set-funded', auth, roleCheck('parent'), setRewardFunded)
router.patch('/:id/refund-all', auth, roleCheck('parent'), refundAllContributions)
router.patch('/:id/cancel', auth, roleCheck('parent'), cancelReward)
router.patch('/:id/archive', auth, roleCheck('parent'), archiveReward)
router.post('/:id/contribute', auth, roleCheck('child'), validate(contributeSchema), contributeToReward)
router.get('/:id/progress', auth, roleCheck('parent'), getRewardProgress)
router.post('/:id/redeem', auth, roleCheck('parent'), redeemReward)
router.patch('/:id/request-refund', auth, roleCheck('child'), requestContributionRefund)
router.patch('/:id/cancel-refund', auth, roleCheck('child'), cancelContributionRefund)
router.patch('/:id/approve-refund/:childId', auth, roleCheck('parent'), approveContributionRefund)
router.patch('/:id/reject-refund/:childId', auth, roleCheck('parent'), rejectContributionRefund)
router.get('/:id/notes', auth, roleCheck('parent'), getRewardNotes)
router.post('/:id/notes', auth, roleCheck('parent'), validate(createRewardNoteSchema), addRewardNote)

module.exports = router